const GLOBAL_CHAT = "GLOBAL_CHAT";
const NEW_GLOBAL_CHAT_MESSAGE = "NEW_GLOBAL_CHAT_MESSAGE";
const SIGN_UP = "SIGN_UP";
const USER_JOIN_CHAT_EVENT = "USER_JOIN_CHAT_EVENT";
const USER_LEAVE_CHAT_EVENT = "USER_LEAVE_CHAT_EVENT";

module.exports = {
  GLOBAL_CHAT,
  NEW_GLOBAL_CHAT_MESSAGE,
  SIGN_UP,
  USER_JOIN_CHAT_EVENT,
  USER_LEAVE_CHAT_EVENT,
};
